<?php

namespace OC\PlateformBundle\Repository;

/**
 * oc_imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class oc_imageRepository extends \Doctrine\ORM\EntityRepository
{
}
